const { cmd, Config, ui } = require('../lib');
cmd(
    {
        pattern: 'song2',
        react: '🎧',
        alias: ['son2', '𝚢𝚝2'],
        desc: 'Downloads audio from youtube.',
        category: 'downloader',
        filename: __filename,
        use: '<text>',
    },
    async (Void, citel, text) => {
        let yts = require('secktor-pack');
        let textYt;
        if (text.startsWith('https://youtube.com/shorts/')) {
            const svid = text.replace('https://youtube.com/shorts/', 'https://youtube.com/v=');
            const s2vid = svid.split('?feature')[0];
            textYt = s2vid;
        } else {
            textYt = text;
        }
        let search = await yts(textYt);
        let anu = search.videos[0];
        let buttonMessaged = {
            image: {
                url: anu.thumbnail,
            },
            caption: `

🎧 𝐗𝐋𝐈𝐂𝐎𝐍-𝐌𝐃 𝗦𝗢𝗡𝗚 𝗗𝗢𝗪𝗡𝗟𝗢𝗗𝗘𝗥🎧
 ◨┉━━━━╚◭☬◮╝━━━━━┉◧

╏🎀 *Title:* ${anu.title}
⦁
╏🌐 *Duration:* ${anu.timestamp}
⦁
╏👀 *Viewers:* ${anu.views}
⦁
╏⬆️ *Uploaded:* ${anu.ago}
⦁
╏👽 *Author:* ${anu.author.name}
⦁
╏📡 *Url* : ${anu.url}

◯┉━━┅━━━━━━━━━┅━━━┉◯

*𝐀𝐔𝐃 ╏ AUDIO* 🎧
*𝐃𝐎𝐂 ╏ DOCUMENT* 📂

◯┉━━┅━━━━━━━━━┅━━━┉◯
 © *_Generated By ${Config.botname}_*
`,
            footer: ui.text.footer,
            headerType: 4,
        };
        await Void.sendMessage(citel.chat, buttonMessaged, {
            quoted: citel,
        });
    },
);
